# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Publish Graduation Capstone Project | © 2022 by fptu-team-404-not-found

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build project with Ant
        run: ant -noinput -buildfile cd /PublishGraduationCapstone/build.xml
		
      - name: Distribute jar-war file
        run: mkdir staging && cp dist/*.jar staging

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: 1.0-SNAPSHOT.jar

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tienhuynh-tn'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1715195CA61E4C9EB9966FE024BEDC2F }}
          package: '*.war'
